### ISSUE TITLE
bubble

### ISSUE THREAD

**Issue by Harsh4598** [aagarwal1012/IntroViews-Flutter#72] opened 2020-08-21 10:00 UTC
hello sir,
            You have done a great job by making this but I have one suggestion to give you  that add new property of asking number of bubble shows at once because as we have more number of intro screen , bubble got on the next and back button and you can keep default value as 3. it looks good to show 3 bubble at once inspite of having any number of intro screen. and the size of bubble increased so many as come on that page. it should be somewhat small .Remaining  everything is all good.

thank you.

**Comment by mzdm** [comment] 2021-04-07 12:58
Closing as duplicate of #24 which tracks bubble/indicator customization. Please follow up there, thanks.

**Closed by mzdm** 2021-04-07 12:58 UTC
Labels: enhancement
