### ISSUE TITLE
Safe area - It doesn't render properly on iPhones with notch

### ISSUE THREAD

**Issue by uwagh** [aagarwal1012/IntroViews-Flutter#30] opened 2019-03-24 20:05 UTC
**Describe the bug**
Safe area - It doesn't render properly on iPhones with notch

**To Reproduce**
1. Run on any iPhone devices with a notch

**Expected behavior**
Implement safe area

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhoneX

**Comment by aagarwal1012** [comment] 2019-03-25 13:40
@uwagh, can you post some screenshots?

**Comment by Ahmadre** [comment] 2019-04-10 10:56
Just add: 
`SafeArea(
    child: new IntroSlider(...)
);
`
to your build method ^^ that is not a bug, you just forgot to wrap it in a SafeArea

**Comment by marianoarga** [comment] 2019-07-16 14:34
@Ahmadre 's Fix works

**Comment by aagarwal1012** [comment] 2019-07-16 15:35
@marianoarga, thanks for the confirmation. Now, I am closing this issue.

**Closed by aagarwal1012** 2019-07-16 15:35 UTC
Labels: question
